# Site
title: Fake it till you make it						# 必填，输入网站标题
subtitle: 					# 此处可不填，子标题
description: 				# 此处可不填，网站简介
keywords: 					# 此处可不填，关键词
author: Gweek  					# 必填，作者名称
language: zh-CN				# 必填，使用的语言，这里应填为 `zh-CN` 
timezone: 'Asia/Shanghai'	# 必填，时区，在国内建议选择上海时间

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://gg.myla.eu.org 	# 必填，Github Page 的地址
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
theme: redefine	# 请在此处修改主题名称，比如：redefine
